version: '3'
services:
  money-tracker-server:
    container_name: money-tracker-server
    image: money-tracker-server:latest
    restart: always
    ports:
      - 8888:80
    environment:
      - JWT_SECRET=
      - DATABASE_URL=
      - GOOGLE_CLIENT_ID=
      - GOOGLE_CLIENT_SECRET=
      - GOOGLE_CALLBACK_URL=
    depends_on:
      - postgres

  postgres:
    container_name: postgres
    image: postgres:13.3
    environment:
      POSTGRES_DB: 'money-tracker-db'
      POSTGRES_USER: 'andreidergavko'
      POSTGRES_PASSWORD: 'andreidergavko'
    volumes:
      - ./postgres:/docker-entrypoint-initdb.d
    ports:
      - 5432:5432
